version: '3.4'

services:
  aspnetvndb:
     image: mcr.microsoft.com/mssql/server

  aspnetvnbasics:
    image: ${DOCKER_REGISTRY-}aspnetvnbasics
    build:
      context: .
      dockerfile: AspnetVnBasics/Dockerfile